# Generated by Django 4.2.1 on 2023-06-03 10:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [

    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50, verbose_name='Название')),
                ('anons', models.CharField(default='', max_length=250, verbose_name='Анонс')),
                ('full_text', models.TextField(verbose_name='Статья')),
                ('date', models.DateTimeField(verbose_name='Дата публикации')),
            ],
        ),
        migrations.CreateModel(
            name='Prepod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(default='', max_length=150, verbose_name='ФИО преподавателя')),
                ('spec', models.CharField(default='', max_length=150, verbose_name='Направление')),
                ('discipline', models.CharField(default='', max_length=150, verbose_name='Дисциплины')),
            ],
        ),
        migrations.CreateModel(
            name='Spravki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0), verbose_name='Дата')),
                ('FIO', models.CharField(default='', max_length=250, verbose_name='ФИО')),
                ('stip', models.IntegerField(default=0, verbose_name='Стипендия')),
                ('dest', models.CharField(default='', max_length=250, verbose_name='Куда направлен')),
            ],
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(default='', max_length=50, verbose_name='Группа')),
                ('spec', models.CharField(default='', max_length=50, verbose_name='Направление')),
                ('num_of_stds', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FIO', models.CharField(default='', max_length=250, verbose_name='ФИО')),
                ('group', models.CharField(default='', max_length=50, verbose_name='Группа')),
            ],
        ),
        migrations.CreateModel(
            name='Disciplines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=150, verbose_name='Название')),
                ('spec', models.CharField(default='', max_length=50, verbose_name='Направление')),
                ('prepod', models.CharField(default='', max_length=150, verbose_name='ФИО преподавателя')),
            ],
        ),
        migrations.AddField(
            model_name='students',
            name='id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.students'),
        ),
        migrations.AddField(
            model_name='prepods',
            name='prepod_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.prepods'),
        ),
    ]
